name: Deploy to Ubuntu VPS

on:
 push:
    branches:
      - main # Trigger on push to main branch

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls -la

      - name: Copy Dockerfile to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /dockerized/containers/rentered_zen
            if [ -f Dockerfile ]; then
              cp Dockerfile /dockerized/containers/rentered_zen/Dockerfile
            else
              echo "Error: Dockerfile not found."
              exit 1
            fi
